trigger:
- main
- develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ShowModifiedFiles
  displayName: 'Show Modified Files'
  steps:
  
  - checkout: self
    fetchDepth: 2
    displayName: 'Checkout Repository'
  
  - script: |
      git show --name-only --pretty=format:""
    displayName: 'Show Modified Files'
